In [19]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:80% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:10pt;}
div.output {font-size:10pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:10pt;}
div.prompt {min-width:80px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:10pt;padding:5px;}
table.dataframe{font-size:14px;}
</style>
"""))

<font size="6" color="green">ch11. 데이터프레임과 시리즈(Pandas)</font>
- pip install pandas (아나콘다 프롬프트)

# 1절. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈 / 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 : 데이터 프레임 생성, 파일 i/o, 레이블링, 부분 데이터 추출, 크기변경(행이나 열 삽입 삭제)
              데이퍼 분할, 병합, 데이터 정렬, 결측치 처리, 피벗과 언피벗 등이 용이
- https://pandas.pydata.org/docs/ (API reference)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [10]:
data = pd.read_json('Data/ch09_member1.json')
# , encoding = 'utf-8' 판다스 read함수의 기본 encoding은 utf-8
display(data)
print(type(data))

  name  age    email   address job
0  홍길동   20  h@h.com   서울시 관악구   -
1  신길동   40  s@h.com  서울시 영등포구  팀장
2  김길동   30  k@h.com   서울시 동작구   -

<class 'pandas.core.frame.DataFrame'>

In [13]:
member4 = pd.read_csv('Data/ch09_member4.csv') # 해더가 있는 csv
member4

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

In [22]:
member1 = pd.read_csv('Data/ch09_member1.csv', 
                     header=None
                     names=['이름', '나이', '메일', '주소'])
member1

     0   1                 2         3
0  홍길동  20  kildong@hong.com   서울시 관악구
1  김길동  40  kimdong@hong.com  서울시 영등포구
2  신길동  30  sindong@hong.com   서울시 동작구

In [23]:
pd.read_hdf('Data/ch09_iris.h5', key='iris')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2절. 데이터 프레임 만들기

## 2.1 딕셔너리를 이용해서 데이터 프레임 만들기

In [25]:
d = {'kor':[100,90], 'mat':[95, 90]}
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   95
1   90   90

In [26]:
df.to_dict() # 데이터프레임을 딕셔너리로 만듦

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 90}}

In [27]:
df.to_numpy() # 데이터프레임을 넘파이배열로 만듦

array([[100,  95],
       [ 90,  90]], dtype=int64)

In [29]:
d = [{'kor': 100, 'mat' : 95},
    {'kor': 90, 'mat' : 99}]
df = pd.DataFrame(d) # 데이터프레임의 열은 동일 자료형
df

   kor  mat
0  100   95
1   90   99

In [30]:
df.dtypes # 데이터프레임의 열별 타입

kor    int64
mat    int64
dtype: object

In [31]:
df.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes

In [40]:
import numpy as np
df['kor'] = df['kor'].astype(np.float64) # 데이터프레임의 열 타입 변경
df

     kor  mat
0  100.0   95
1   90.0   99

In [41]:
d = [{'kor': 100, 'mat':100},
    {'kor': 90, 'mat': 99},
    {'kor': 80, 'eng': 85}]
df = pd.DataFrame(data = d)
df

   kor    mat   eng
0  100  100.0   NaN
1   90   99.0   NaN
2   80    NaN  85.0

In [42]:
type(np.nan) # 결측치의 타임 : float

float

In [ ]:
# 결측치는 int로 형변환이 불가
df['mat'].astype(np.int32)

## 2.2 리스트를 이용해서 데이터프레임 만들기

In [43]:
kor = [100, 90, 80, 70, 60]
mat = [90, 91, 81, 71, 61]
df = pd.DataFrame({'kor':kor, 'mat': mat})
df

   kor  mat
0  100   90
1   90   91
2   80   81
3   70   71
4   60   61

In [49]:
pd.DataFrame(np.c_[kor, mat], columns=['kor', 'mat'])

   kor  mat
0  100   90
1   90   91
2   80   81
3   70   71
4   60   61

In [52]:
l = [[100, 90], [70, 80]]
pd.DataFrame(l, columns = ['국어', '수학'])

    국어  수학
0  100  90
1   70  80

- data.go.kr에서 "상가상권 정보" 다운로드 / "민간 아파트 분양가격" 다운로드

In [67]:
%ls "C:\ai\Downloads\shareData\상가정보\"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 1828-3575

 C:\ai\Downloads\shareData\상가정보 디렉터리

2026-07-14  오후 05:39    <DIR>          .
2026-07-14  오후 05:39    <DIR>          ..
2025-11-03  오전 12:45             1,011 [필독]파일열람방법.txt
2026-04-27  오전 11:10        61,321,696 소상공인시장진흥공단_상가(상권)정보_강원_202603.csv
2026-04-27  오전 11:10       367,852,181 소상공인시장진흥공단_상가(상권)정보_경기_202603.csv
2026-04-27  오전 11:10        92,474,293 소상공인시장진흥공단_상가(상권)정보_경남_202603.csv
2026-04-27  오전 11:10        76,309,810 소상공인시장진흥공단_상가(상권)정보_경북_202603.csv
2026-04-27  오전 11:10        40,031,721 소상공인시장진흥공단_상가(상권)정보_광주_202603.csv
2026-04-27  오전 11:10        61,825,564 소상공인시장진흥공단_상가(상권)정보_대구_202603.csv
2026-04-27  오전 11:10        41,866,930 소상공인시장진흥공단_상가(상권)정보_대전_202603.csv
2026-04-27  오전 11:10        84,329,596 소상공인시장진흥공단_상가(상권)정보_부산_202603.csv
2026-04-27  오전 11:10       292,646,735 소상공인시장진흥공단_상가(상권)정보_서울_202603.csv
2026-04-27  오전 11:10         9,651,297 소상공인시장진흥공단_상가(상권)정보_세종_202603.csv
2026-04-27  오전 11:10        28,285,232 소상공인시장진흥공단_상가(상권)정보_울산_202603.csv
2026-04-27  오전 11:10        74,007,608 소상공인시장진흥공단_상가(상권)정보_인천_202603.csv
2026-04-27  오전 11:10        53,165,985 소상공인시장진흥공단_상가(상권)정보_전남_202603.csv
2026-04-27  오전 11:10        56,632,709 소상공인시장진흥공단_상가(상권)정보_전북_202603.csv
2026-04-27  오전 11:10        32,746,698 소상공인시장진흥공단_상가(상권)정보_제주_202603.csv
2026-04-27  오전 11:10        66,764,669 소상공인시장진흥공단_상가(상권)정보_충남_202603.csv
2026-04-27  오전 11:10        50,941,247 소상공인시장진흥공단_상가(상권)정보_충북_202603.csv
              18개 파일       1,490,854,982 바이트
               2개 디렉터리  779,890,880,512 바이트 남음

In [70]:
df = pd.read_csv(r'C:\ai\Downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_세종_202603.csv',
               # encoding = 'utf-8', sep=','
                nrows=30, # 처음 30행만 가져오기
                low_memory=False, # 데이터 용량이 클 경우 기입
                )
df.shape # 30행 39열

(30, 39)

In [71]:
df.head(1) # 상위 1행

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220813963449,레인카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4473025021101010001038753,NaN,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,339883.0,30027,NaN,지,NaN,127.300453,36.600906

In [77]:
# 판다스 display옵션
pd.options.display.max_columns = 39 # 39열까지 display
pd.options.display.max_rows = 40 # 30행까지 display

In [79]:
df.head(2).T

                                       0                                1
상가업소번호              MA010120220813963449             MA010120220805872513
상호명                                 레인카페                             수와마을
지점명                                  NaN                              NaN
상권업종대분류코드                             I2                               I2
상권업종대분류명                              음식                               음식
상권업종중분류코드                           I212                             I201
상권업종중분류명                           비알코올                                한식
상권업종소분류코드                         I21201                           I20101
상권업종소분류명                              카페                           백반/한정식
표준산업분류코드                          I56229                           I56111
표준산업분류명                     기타 비알코올 음료점업                       한식 일반 음식점업
시도코드                                  36                               36
시도명                              세종특별자치시                          세종특별자치시
시군구코드                              36110                            36110
시군구명                             세종특별자치시                          세종특별자치시
행정동코드                           36110250                         36110250
행정동명                                조치원읍                             조치원읍
법정동코드                         3611025021                       3611025030
법정동명                                조치원읍                             조치원읍
지번코드                 3611025021101010001              3611025030103790016
대지구분코드                                 1                                1
대지구분명                                 대지                               대지
지번본번지                                101                              379
지번부번지                                1.0                             16.0
지번주소       세종특별자치시 세종특별자치시 조치원읍 원리 101-1  세종특별자치시 세종특별자치시 조치원읍 죽림리 379-16
도로명코드                       361104574473                     361103258034
도로명           세종특별자치시 세종특별자치시 조치원읍 조치원8길         세종특별자치시 세종특별자치시 조치원읍 충현로
건물본번지                                 16                               75
건물부번지                                NaN                              1.0
건물관리번호         4473025021101010001038753        4473025030103790016042253
건물명                                  NaN                              NaN
도로명주소      세종특별자치시 세종특별자치시 조치원읍 조치원8길 16    세종특별자치시 세종특별자치시 조치원읍 충현로 75-1
구우편번호                           339883.0                         339884.0
신우편번호                              30027                            30034
동정보                                  NaN                              NaN
층정보                                    지                              NaN
호정보                                  NaN                              NaN
경도                            127.300453                       127.296263
위도                             36.600906                        36.595303